<?php
/**
 * SignupPageSignup
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SignupPageSignup Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SignupPageSignup implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SignupPageSignup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'account' => '\Swagger\Client\Model\Account',
        'subscription' => '\Swagger\Client\Model\PreparedSubscription',
        'locale' => 'string',
        'cancel_url' => 'string',
        'accept_url' => 'string',
        'plan' => '\Swagger\Client\Model\Plan',
        'discounts' => '\Swagger\Client\Model\Discount[]',
        'add_ons' => '\Swagger\Client\Model\AddOn[]',
        'email' => 'string',
        'phone' => 'string',
        'address' => 'string',
        'company' => 'string',
        'city' => 'string',
        'coupon' => 'string',
        'amount' => 'int',
        'quantity' => 'int',
        'subscription_configuration' => '\Swagger\Client\Model\CreateSubscription',
        'first_name' => 'string',
        'last_name' => 'string',
        'postal_code' => 'string',
        'amount_incl_vat' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'account' => null,
        'subscription' => null,
        'locale' => null,
        'cancel_url' => null,
        'accept_url' => null,
        'plan' => null,
        'discounts' => null,
        'add_ons' => null,
        'email' => null,
        'phone' => null,
        'address' => null,
        'company' => null,
        'city' => null,
        'coupon' => null,
        'amount' => 'int32',
        'quantity' => 'int32',
        'subscription_configuration' => null,
        'first_name' => null,
        'last_name' => null,
        'postal_code' => null,
        'amount_incl_vat' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account' => 'account',
        'subscription' => 'subscription',
        'locale' => 'locale',
        'cancel_url' => 'cancelUrl',
        'accept_url' => 'acceptUrl',
        'plan' => 'plan',
        'discounts' => 'discounts',
        'add_ons' => 'addOns',
        'email' => 'email',
        'phone' => 'phone',
        'address' => 'address',
        'company' => 'company',
        'city' => 'city',
        'coupon' => 'coupon',
        'amount' => 'amount',
        'quantity' => 'quantity',
        'subscription_configuration' => 'subscription_configuration',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'postal_code' => 'postal_code',
        'amount_incl_vat' => 'amount_incl_vat'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'account' => 'setAccount',
        'subscription' => 'setSubscription',
        'locale' => 'setLocale',
        'cancel_url' => 'setCancelUrl',
        'accept_url' => 'setAcceptUrl',
        'plan' => 'setPlan',
        'discounts' => 'setDiscounts',
        'add_ons' => 'setAddOns',
        'email' => 'setEmail',
        'phone' => 'setPhone',
        'address' => 'setAddress',
        'company' => 'setCompany',
        'city' => 'setCity',
        'coupon' => 'setCoupon',
        'amount' => 'setAmount',
        'quantity' => 'setQuantity',
        'subscription_configuration' => 'setSubscriptionConfiguration',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'postal_code' => 'setPostalCode',
        'amount_incl_vat' => 'setAmountInclVat'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account' => 'getAccount',
        'subscription' => 'getSubscription',
        'locale' => 'getLocale',
        'cancel_url' => 'getCancelUrl',
        'accept_url' => 'getAcceptUrl',
        'plan' => 'getPlan',
        'discounts' => 'getDiscounts',
        'add_ons' => 'getAddOns',
        'email' => 'getEmail',
        'phone' => 'getPhone',
        'address' => 'getAddress',
        'company' => 'getCompany',
        'city' => 'getCity',
        'coupon' => 'getCoupon',
        'amount' => 'getAmount',
        'quantity' => 'getQuantity',
        'subscription_configuration' => 'getSubscriptionConfiguration',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'postal_code' => 'getPostalCode',
        'amount_incl_vat' => 'getAmountInclVat'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const EMAIL_HIDDEN = 'HIDDEN';
    const EMAIL_OPTIONAL = 'OPTIONAL';
    const EMAIL_MANDATORY = 'MANDATORY';
    const PHONE_HIDDEN = 'HIDDEN';
    const PHONE_OPTIONAL = 'OPTIONAL';
    const PHONE_MANDATORY = 'MANDATORY';
    const ADDRESS_HIDDEN = 'HIDDEN';
    const ADDRESS_OPTIONAL = 'OPTIONAL';
    const ADDRESS_MANDATORY = 'MANDATORY';
    const COMPANY_HIDDEN = 'HIDDEN';
    const COMPANY_OPTIONAL = 'OPTIONAL';
    const COMPANY_MANDATORY = 'MANDATORY';
    const CITY_HIDDEN = 'HIDDEN';
    const CITY_OPTIONAL = 'OPTIONAL';
    const CITY_MANDATORY = 'MANDATORY';
    const COUPON_HIDDEN = 'HIDDEN';
    const COUPON_OPTIONAL = 'OPTIONAL';
    const COUPON_MANDATORY = 'MANDATORY';
    const FIRST_NAME_HIDDEN = 'HIDDEN';
    const FIRST_NAME_OPTIONAL = 'OPTIONAL';
    const FIRST_NAME_MANDATORY = 'MANDATORY';
    const LAST_NAME_HIDDEN = 'HIDDEN';
    const LAST_NAME_OPTIONAL = 'OPTIONAL';
    const LAST_NAME_MANDATORY = 'MANDATORY';
    const POSTAL_CODE_HIDDEN = 'HIDDEN';
    const POSTAL_CODE_OPTIONAL = 'OPTIONAL';
    const POSTAL_CODE_MANDATORY = 'MANDATORY';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getEmailAllowableValues()
    {
        return [
            self::EMAIL_HIDDEN,
            self::EMAIL_OPTIONAL,
            self::EMAIL_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPhoneAllowableValues()
    {
        return [
            self::PHONE_HIDDEN,
            self::PHONE_OPTIONAL,
            self::PHONE_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAddressAllowableValues()
    {
        return [
            self::ADDRESS_HIDDEN,
            self::ADDRESS_OPTIONAL,
            self::ADDRESS_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCompanyAllowableValues()
    {
        return [
            self::COMPANY_HIDDEN,
            self::COMPANY_OPTIONAL,
            self::COMPANY_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCityAllowableValues()
    {
        return [
            self::CITY_HIDDEN,
            self::CITY_OPTIONAL,
            self::CITY_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCouponAllowableValues()
    {
        return [
            self::COUPON_HIDDEN,
            self::COUPON_OPTIONAL,
            self::COUPON_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFirstNameAllowableValues()
    {
        return [
            self::FIRST_NAME_HIDDEN,
            self::FIRST_NAME_OPTIONAL,
            self::FIRST_NAME_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLastNameAllowableValues()
    {
        return [
            self::LAST_NAME_HIDDEN,
            self::LAST_NAME_OPTIONAL,
            self::LAST_NAME_MANDATORY,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPostalCodeAllowableValues()
    {
        return [
            self::POSTAL_CODE_HIDDEN,
            self::POSTAL_CODE_OPTIONAL,
            self::POSTAL_CODE_MANDATORY,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account'] = isset($data['account']) ? $data['account'] : null;
        $this->container['subscription'] = isset($data['subscription']) ? $data['subscription'] : null;
        $this->container['locale'] = isset($data['locale']) ? $data['locale'] : null;
        $this->container['cancel_url'] = isset($data['cancel_url']) ? $data['cancel_url'] : null;
        $this->container['accept_url'] = isset($data['accept_url']) ? $data['accept_url'] : null;
        $this->container['plan'] = isset($data['plan']) ? $data['plan'] : null;
        $this->container['discounts'] = isset($data['discounts']) ? $data['discounts'] : null;
        $this->container['add_ons'] = isset($data['add_ons']) ? $data['add_ons'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['company'] = isset($data['company']) ? $data['company'] : null;
        $this->container['city'] = isset($data['city']) ? $data['city'] : null;
        $this->container['coupon'] = isset($data['coupon']) ? $data['coupon'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['quantity'] = isset($data['quantity']) ? $data['quantity'] : null;
        $this->container['subscription_configuration'] = isset($data['subscription_configuration']) ? $data['subscription_configuration'] : null;
        $this->container['first_name'] = isset($data['first_name']) ? $data['first_name'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['postal_code'] = isset($data['postal_code']) ? $data['postal_code'] : null;
        $this->container['amount_incl_vat'] = isset($data['amount_incl_vat']) ? $data['amount_incl_vat'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getEmailAllowableValues();
        if (!is_null($this->container['email']) && !in_array($this->container['email'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'email', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPhoneAllowableValues();
        if (!is_null($this->container['phone']) && !in_array($this->container['phone'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'phone', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getAddressAllowableValues();
        if (!is_null($this->container['address']) && !in_array($this->container['address'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'address', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCompanyAllowableValues();
        if (!is_null($this->container['company']) && !in_array($this->container['company'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'company', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCityAllowableValues();
        if (!is_null($this->container['city']) && !in_array($this->container['city'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'city', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getCouponAllowableValues();
        if (!is_null($this->container['coupon']) && !in_array($this->container['coupon'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'coupon', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getFirstNameAllowableValues();
        if (!is_null($this->container['first_name']) && !in_array($this->container['first_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'first_name', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLastNameAllowableValues();
        if (!is_null($this->container['last_name']) && !in_array($this->container['last_name'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'last_name', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getPostalCodeAllowableValues();
        if (!is_null($this->container['postal_code']) && !in_array($this->container['postal_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'postal_code', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets account
     *
     * @return \Swagger\Client\Model\Account
     */
    public function getAccount()
    {
        return $this->container['account'];
    }

    /**
     * Sets account
     *
     * @param \Swagger\Client\Model\Account $account account
     *
     * @return $this
     */
    public function setAccount($account)
    {
        $this->container['account'] = $account;

        return $this;
    }

    /**
     * Gets subscription
     *
     * @return \Swagger\Client\Model\PreparedSubscription
     */
    public function getSubscription()
    {
        return $this->container['subscription'];
    }

    /**
     * Sets subscription
     *
     * @param \Swagger\Client\Model\PreparedSubscription $subscription subscription
     *
     * @return $this
     */
    public function setSubscription($subscription)
    {
        $this->container['subscription'] = $subscription;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string $locale locale
     *
     * @return $this
     */
    public function setLocale($locale)
    {
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets cancel_url
     *
     * @return string
     */
    public function getCancelUrl()
    {
        return $this->container['cancel_url'];
    }

    /**
     * Sets cancel_url
     *
     * @param string $cancel_url cancel_url
     *
     * @return $this
     */
    public function setCancelUrl($cancel_url)
    {
        $this->container['cancel_url'] = $cancel_url;

        return $this;
    }

    /**
     * Gets accept_url
     *
     * @return string
     */
    public function getAcceptUrl()
    {
        return $this->container['accept_url'];
    }

    /**
     * Sets accept_url
     *
     * @param string $accept_url accept_url
     *
     * @return $this
     */
    public function setAcceptUrl($accept_url)
    {
        $this->container['accept_url'] = $accept_url;

        return $this;
    }

    /**
     * Gets plan
     *
     * @return \Swagger\Client\Model\Plan
     */
    public function getPlan()
    {
        return $this->container['plan'];
    }

    /**
     * Sets plan
     *
     * @param \Swagger\Client\Model\Plan $plan plan
     *
     * @return $this
     */
    public function setPlan($plan)
    {
        $this->container['plan'] = $plan;

        return $this;
    }

    /**
     * Gets discounts
     *
     * @return \Swagger\Client\Model\Discount[]
     */
    public function getDiscounts()
    {
        return $this->container['discounts'];
    }

    /**
     * Sets discounts
     *
     * @param \Swagger\Client\Model\Discount[] $discounts discounts
     *
     * @return $this
     */
    public function setDiscounts($discounts)
    {
        $this->container['discounts'] = $discounts;

        return $this;
    }

    /**
     * Gets add_ons
     *
     * @return \Swagger\Client\Model\AddOn[]
     */
    public function getAddOns()
    {
        return $this->container['add_ons'];
    }

    /**
     * Sets add_ons
     *
     * @param \Swagger\Client\Model\AddOn[] $add_ons add_ons
     *
     * @return $this
     */
    public function setAddOns($add_ons)
    {
        $this->container['add_ons'] = $add_ons;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $allowedValues = $this->getEmailAllowableValues();
        if (!is_null($email) && !in_array($email, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'email', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone phone
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $allowedValues = $this->getPhoneAllowableValues();
        if (!is_null($phone) && !in_array($phone, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'phone', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param string $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $allowedValues = $this->getAddressAllowableValues();
        if (!is_null($address) && !in_array($address, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'address', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets company
     *
     * @return string
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     *
     * @param string $company company
     *
     * @return $this
     */
    public function setCompany($company)
    {
        $allowedValues = $this->getCompanyAllowableValues();
        if (!is_null($company) && !in_array($company, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'company', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets city
     *
     * @return string
     */
    public function getCity()
    {
        return $this->container['city'];
    }

    /**
     * Sets city
     *
     * @param string $city city
     *
     * @return $this
     */
    public function setCity($city)
    {
        $allowedValues = $this->getCityAllowableValues();
        if (!is_null($city) && !in_array($city, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'city', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['city'] = $city;

        return $this;
    }

    /**
     * Gets coupon
     *
     * @return string
     */
    public function getCoupon()
    {
        return $this->container['coupon'];
    }

    /**
     * Sets coupon
     *
     * @param string $coupon coupon
     *
     * @return $this
     */
    public function setCoupon($coupon)
    {
        $allowedValues = $this->getCouponAllowableValues();
        if (!is_null($coupon) && !in_array($coupon, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'coupon', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['coupon'] = $coupon;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount amount
     *
     * @return $this
     */
    public function setAmount($amount)
    {
        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets quantity
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->container['quantity'];
    }

    /**
     * Sets quantity
     *
     * @param int $quantity quantity
     *
     * @return $this
     */
    public function setQuantity($quantity)
    {
        $this->container['quantity'] = $quantity;

        return $this;
    }

    /**
     * Gets subscription_configuration
     *
     * @return \Swagger\Client\Model\CreateSubscription
     */
    public function getSubscriptionConfiguration()
    {
        return $this->container['subscription_configuration'];
    }

    /**
     * Sets subscription_configuration
     *
     * @param \Swagger\Client\Model\CreateSubscription $subscription_configuration subscription_configuration
     *
     * @return $this
     */
    public function setSubscriptionConfiguration($subscription_configuration)
    {
        $this->container['subscription_configuration'] = $subscription_configuration;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string $first_name first_name
     *
     * @return $this
     */
    public function setFirstName($first_name)
    {
        $allowedValues = $this->getFirstNameAllowableValues();
        if (!is_null($first_name) && !in_array($first_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'first_name', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string $last_name last_name
     *
     * @return $this
     */
    public function setLastName($last_name)
    {
        $allowedValues = $this->getLastNameAllowableValues();
        if (!is_null($last_name) && !in_array($last_name, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'last_name', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets postal_code
     *
     * @return string
     */
    public function getPostalCode()
    {
        return $this->container['postal_code'];
    }

    /**
     * Sets postal_code
     *
     * @param string $postal_code postal_code
     *
     * @return $this
     */
    public function setPostalCode($postal_code)
    {
        $allowedValues = $this->getPostalCodeAllowableValues();
        if (!is_null($postal_code) && !in_array($postal_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'postal_code', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['postal_code'] = $postal_code;

        return $this;
    }

    /**
     * Gets amount_incl_vat
     *
     * @return bool
     */
    public function getAmountInclVat()
    {
        return $this->container['amount_incl_vat'];
    }

    /**
     * Sets amount_incl_vat
     *
     * @param bool $amount_incl_vat amount_incl_vat
     *
     * @return $this
     */
    public function setAmountInclVat($amount_incl_vat)
    {
        $this->container['amount_incl_vat'] = $amount_incl_vat;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


