<?php
/**
 * Transaction
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * Transaction Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class Transaction implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'Transaction';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'state' => 'string',
        'invoice' => 'string',
        'type' => 'string',
        'amount' => 'int',
        'settled' => '\DateTime',
        'authorized' => '\DateTime',
        'failed' => '\DateTime',
        'refunded' => '\DateTime',
        'created' => '\DateTime',
        'card_transaction' => '\Swagger\Client\Model\CardTransaction',
        'mpo_transaction' => '\Swagger\Client\Model\CardTransaction',
        'applepay_transaction' => '\Swagger\Client\Model\CardTransaction',
        'googlepay_transaction' => '\Swagger\Client\Model\CardTransaction',
        'manual_transaction' => '\Swagger\Client\Model\ManualTransaction',
        'viabill_transaction' => '\Swagger\Client\Model\ViabillTransaction',
        'resurs_transaction' => '\Swagger\Client\Model\ResursTransaction',
        'paypal_transaction' => '\Swagger\Client\Model\PaypalTransaction',
        'pgw_transaction' => '\Swagger\Client\Model\PgwTransaction'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'state' => null,
        'invoice' => null,
        'type' => null,
        'amount' => 'int32',
        'settled' => 'date-time',
        'authorized' => 'date-time',
        'failed' => 'date-time',
        'refunded' => 'date-time',
        'created' => 'date-time',
        'card_transaction' => null,
        'mpo_transaction' => null,
        'applepay_transaction' => null,
        'googlepay_transaction' => null,
        'manual_transaction' => null,
        'viabill_transaction' => null,
        'resurs_transaction' => null,
        'paypal_transaction' => null,
        'pgw_transaction' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'state' => 'state',
        'invoice' => 'invoice',
        'type' => 'type',
        'amount' => 'amount',
        'settled' => 'settled',
        'authorized' => 'authorized',
        'failed' => 'failed',
        'refunded' => 'refunded',
        'created' => 'created',
        'card_transaction' => 'card_transaction',
        'mpo_transaction' => 'mpo_transaction',
        'applepay_transaction' => 'applepay_transaction',
        'googlepay_transaction' => 'googlepay_transaction',
        'manual_transaction' => 'manual_transaction',
        'viabill_transaction' => 'viabill_transaction',
        'resurs_transaction' => 'resurs_transaction',
        'paypal_transaction' => 'paypal_transaction',
        'pgw_transaction' => 'pgw_transaction'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'state' => 'setState',
        'invoice' => 'setInvoice',
        'type' => 'setType',
        'amount' => 'setAmount',
        'settled' => 'setSettled',
        'authorized' => 'setAuthorized',
        'failed' => 'setFailed',
        'refunded' => 'setRefunded',
        'created' => 'setCreated',
        'card_transaction' => 'setCardTransaction',
        'mpo_transaction' => 'setMpoTransaction',
        'applepay_transaction' => 'setApplepayTransaction',
        'googlepay_transaction' => 'setGooglepayTransaction',
        'manual_transaction' => 'setManualTransaction',
        'viabill_transaction' => 'setViabillTransaction',
        'resurs_transaction' => 'setResursTransaction',
        'paypal_transaction' => 'setPaypalTransaction',
        'pgw_transaction' => 'setPgwTransaction'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'state' => 'getState',
        'invoice' => 'getInvoice',
        'type' => 'getType',
        'amount' => 'getAmount',
        'settled' => 'getSettled',
        'authorized' => 'getAuthorized',
        'failed' => 'getFailed',
        'refunded' => 'getRefunded',
        'created' => 'getCreated',
        'card_transaction' => 'getCardTransaction',
        'mpo_transaction' => 'getMpoTransaction',
        'applepay_transaction' => 'getApplepayTransaction',
        'googlepay_transaction' => 'getGooglepayTransaction',
        'manual_transaction' => 'getManualTransaction',
        'viabill_transaction' => 'getViabillTransaction',
        'resurs_transaction' => 'getResursTransaction',
        'paypal_transaction' => 'getPaypalTransaction',
        'pgw_transaction' => 'getPgwTransaction'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    const STATE_PENDING = 'pending';
    const STATE_PROCESSING = 'processing';
    const STATE_AUTHORIZED = 'authorized';
    const STATE_SETTLED = 'settled';
    const STATE_REFUNDED = 'refunded';
    const STATE_FAILED = 'failed';
    const STATE_CANCELLED = 'cancelled';
    const TYPE_SETTLE = 'settle';
    const TYPE_REFUND = 'refund';
    const TYPE_AUTHORIZATION = 'authorization';
    

    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStateAllowableValues()
    {
        return [
            self::STATE_PENDING,
            self::STATE_PROCESSING,
            self::STATE_AUTHORIZED,
            self::STATE_SETTLED,
            self::STATE_REFUNDED,
            self::STATE_FAILED,
            self::STATE_CANCELLED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_SETTLE,
            self::TYPE_REFUND,
            self::TYPE_AUTHORIZATION,
        ];
    }
    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['state'] = isset($data['state']) ? $data['state'] : null;
        $this->container['invoice'] = isset($data['invoice']) ? $data['invoice'] : null;
        $this->container['type'] = isset($data['type']) ? $data['type'] : null;
        $this->container['amount'] = isset($data['amount']) ? $data['amount'] : null;
        $this->container['settled'] = isset($data['settled']) ? $data['settled'] : null;
        $this->container['authorized'] = isset($data['authorized']) ? $data['authorized'] : null;
        $this->container['failed'] = isset($data['failed']) ? $data['failed'] : null;
        $this->container['refunded'] = isset($data['refunded']) ? $data['refunded'] : null;
        $this->container['created'] = isset($data['created']) ? $data['created'] : null;
        $this->container['card_transaction'] = isset($data['card_transaction']) ? $data['card_transaction'] : null;
        $this->container['mpo_transaction'] = isset($data['mpo_transaction']) ? $data['mpo_transaction'] : null;
        $this->container['applepay_transaction'] = isset($data['applepay_transaction']) ? $data['applepay_transaction'] : null;
        $this->container['googlepay_transaction'] = isset($data['googlepay_transaction']) ? $data['googlepay_transaction'] : null;
        $this->container['manual_transaction'] = isset($data['manual_transaction']) ? $data['manual_transaction'] : null;
        $this->container['viabill_transaction'] = isset($data['viabill_transaction']) ? $data['viabill_transaction'] : null;
        $this->container['resurs_transaction'] = isset($data['resurs_transaction']) ? $data['resurs_transaction'] : null;
        $this->container['paypal_transaction'] = isset($data['paypal_transaction']) ? $data['paypal_transaction'] : null;
        $this->container['pgw_transaction'] = isset($data['pgw_transaction']) ? $data['pgw_transaction'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['state'] === null) {
            $invalidProperties[] = "'state' can't be null";
        }
        $allowedValues = $this->getStateAllowableValues();
        if (!is_null($this->container['state']) && !in_array($this->container['state'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'state', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['invoice'] === null) {
            $invalidProperties[] = "'invoice' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value for 'type', must be one of '%s'",
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['amount'] === null) {
            $invalidProperties[] = "'amount' can't be null";
        }
        if (($this->container['amount'] < 0)) {
            $invalidProperties[] = "invalid value for 'amount', must be bigger than or equal to 0.";
        }

        if ($this->container['created'] === null) {
            $invalidProperties[] = "'created' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id Transaction id assigned by Reepay
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets state
     *
     * @return string
     */
    public function getState()
    {
        return $this->container['state'];
    }

    /**
     * Sets state
     *
     * @param string $state State of the transaction, one of the following: `pending`, `processing`, `authorized`, `settled`, `refunded`, `failed`, `cancelled`
     *
     * @return $this
     */
    public function setState($state)
    {
        $allowedValues = $this->getStateAllowableValues();
        if (!in_array($state, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'state', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['state'] = $state;

        return $this;
    }

    /**
     * Gets invoice
     *
     * @return string
     */
    public function getInvoice()
    {
        return $this->container['invoice'];
    }

    /**
     * Sets invoice
     *
     * @param string $invoice Invoice id
     *
     * @return $this
     */
    public function setInvoice($invoice)
    {
        $this->container['invoice'] = $invoice;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type Transaction type, one of the following: 'settle', 'refund', `authorization`
     *
     * @return $this
     */
    public function setType($type)
    {
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'type', must be one of '%s'",
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets amount
     *
     * @return int
     */
    public function getAmount()
    {
        return $this->container['amount'];
    }

    /**
     * Sets amount
     *
     * @param int $amount The transaction amount
     *
     * @return $this
     */
    public function setAmount($amount)
    {

        if (($amount < 0)) {
            throw new \InvalidArgumentException('invalid value for $amount when calling Transaction., must be bigger than or equal to 0.');
        }

        $this->container['amount'] = $amount;

        return $this;
    }

    /**
     * Gets settled
     *
     * @return \DateTime
     */
    public function getSettled()
    {
        return $this->container['settled'];
    }

    /**
     * Sets settled
     *
     * @param \DateTime $settled When the transaction was settled, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
     *
     * @return $this
     */
    public function setSettled($settled)
    {
        $this->container['settled'] = $settled;

        return $this;
    }

    /**
     * Gets authorized
     *
     * @return \DateTime
     */
    public function getAuthorized()
    {
        return $this->container['authorized'];
    }

    /**
     * Sets authorized
     *
     * @param \DateTime $authorized When the transaction was authorized, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
     *
     * @return $this
     */
    public function setAuthorized($authorized)
    {
        $this->container['authorized'] = $authorized;

        return $this;
    }

    /**
     * Gets failed
     *
     * @return \DateTime
     */
    public function getFailed()
    {
        return $this->container['failed'];
    }

    /**
     * Sets failed
     *
     * @param \DateTime $failed When the transaction failed, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
     *
     * @return $this
     */
    public function setFailed($failed)
    {
        $this->container['failed'] = $failed;

        return $this;
    }

    /**
     * Gets refunded
     *
     * @return \DateTime
     */
    public function getRefunded()
    {
        return $this->container['refunded'];
    }

    /**
     * Sets refunded
     *
     * @param \DateTime $refunded When the transaction was refunded, in [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
     *
     * @return $this
     */
    public function setRefunded($refunded)
    {
        $this->container['refunded'] = $refunded;

        return $this;
    }

    /**
     * Gets created
     *
     * @return \DateTime
     */
    public function getCreated()
    {
        return $this->container['created'];
    }

    /**
     * Sets created
     *
     * @param \DateTime $created Date when the transaction was created. In [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601) extended offset date-time format.
     *
     * @return $this
     */
    public function setCreated($created)
    {
        $this->container['created'] = $created;

        return $this;
    }

    /**
     * Gets card_transaction
     *
     * @return \Swagger\Client\Model\CardTransaction
     */
    public function getCardTransaction()
    {
        return $this->container['card_transaction'];
    }

    /**
     * Sets card_transaction
     *
     * @param \Swagger\Client\Model\CardTransaction $card_transaction Specifics in case of card transaction
     *
     * @return $this
     */
    public function setCardTransaction($card_transaction)
    {
        $this->container['card_transaction'] = $card_transaction;

        return $this;
    }

    /**
     * Gets mpo_transaction
     *
     * @return \Swagger\Client\Model\CardTransaction
     */
    public function getMpoTransaction()
    {
        return $this->container['mpo_transaction'];
    }

    /**
     * Sets mpo_transaction
     *
     * @param \Swagger\Client\Model\CardTransaction $mpo_transaction Specifics in case of MobilePay Online transaction
     *
     * @return $this
     */
    public function setMpoTransaction($mpo_transaction)
    {
        $this->container['mpo_transaction'] = $mpo_transaction;

        return $this;
    }

    /**
     * Gets applepay_transaction
     *
     * @return \Swagger\Client\Model\CardTransaction
     */
    public function getApplepayTransaction()
    {
        return $this->container['applepay_transaction'];
    }

    /**
     * Sets applepay_transaction
     *
     * @param \Swagger\Client\Model\CardTransaction $applepay_transaction Specifics in case of ApplePay transaction
     *
     * @return $this
     */
    public function setApplepayTransaction($applepay_transaction)
    {
        $this->container['applepay_transaction'] = $applepay_transaction;

        return $this;
    }

    /**
     * Gets googlepay_transaction
     *
     * @return \Swagger\Client\Model\CardTransaction
     */
    public function getGooglepayTransaction()
    {
        return $this->container['googlepay_transaction'];
    }

    /**
     * Sets googlepay_transaction
     *
     * @param \Swagger\Client\Model\CardTransaction $googlepay_transaction Specifics in case of GooglePay transaction
     *
     * @return $this
     */
    public function setGooglepayTransaction($googlepay_transaction)
    {
        $this->container['googlepay_transaction'] = $googlepay_transaction;

        return $this;
    }

    /**
     * Gets manual_transaction
     *
     * @return \Swagger\Client\Model\ManualTransaction
     */
    public function getManualTransaction()
    {
        return $this->container['manual_transaction'];
    }

    /**
     * Sets manual_transaction
     *
     * @param \Swagger\Client\Model\ManualTransaction $manual_transaction Specifics in case of manual transaction
     *
     * @return $this
     */
    public function setManualTransaction($manual_transaction)
    {
        $this->container['manual_transaction'] = $manual_transaction;

        return $this;
    }

    /**
     * Gets viabill_transaction
     *
     * @return \Swagger\Client\Model\ViabillTransaction
     */
    public function getViabillTransaction()
    {
        return $this->container['viabill_transaction'];
    }

    /**
     * Sets viabill_transaction
     *
     * @param \Swagger\Client\Model\ViabillTransaction $viabill_transaction Specifics in case of ViaBill transaction
     *
     * @return $this
     */
    public function setViabillTransaction($viabill_transaction)
    {
        $this->container['viabill_transaction'] = $viabill_transaction;

        return $this;
    }

    /**
     * Gets resurs_transaction
     *
     * @return \Swagger\Client\Model\ResursTransaction
     */
    public function getResursTransaction()
    {
        return $this->container['resurs_transaction'];
    }

    /**
     * Sets resurs_transaction
     *
     * @param \Swagger\Client\Model\ResursTransaction $resurs_transaction Specifics in case of Resurs Bank transaction
     *
     * @return $this
     */
    public function setResursTransaction($resurs_transaction)
    {
        $this->container['resurs_transaction'] = $resurs_transaction;

        return $this;
    }

    /**
     * Gets paypal_transaction
     *
     * @return \Swagger\Client\Model\PaypalTransaction
     */
    public function getPaypalTransaction()
    {
        return $this->container['paypal_transaction'];
    }

    /**
     * Sets paypal_transaction
     *
     * @param \Swagger\Client\Model\PaypalTransaction $paypal_transaction Specifics in case of PayPal transaction
     *
     * @return $this
     */
    public function setPaypalTransaction($paypal_transaction)
    {
        $this->container['paypal_transaction'] = $paypal_transaction;

        return $this;
    }

    /**
     * Gets pgw_transaction
     *
     * @return \Swagger\Client\Model\PgwTransaction
     */
    public function getPgwTransaction()
    {
        return $this->container['pgw_transaction'];
    }

    /**
     * Sets pgw_transaction
     *
     * @param \Swagger\Client\Model\PgwTransaction $pgw_transaction Specifics in case of generic payment gateway transaction
     *
     * @return $this
     */
    public function setPgwTransaction($pgw_transaction)
    {
        $this->container['pgw_transaction'] = $pgw_transaction;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


