<?php
/**
 * CardOnFileTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CardOnFileTest Class Doc Comment
 *
 * @category    Class
 * @description CardOnFile
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CardOnFileTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CardOnFile"
     */
    public function testCardOnFile()
    {
    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {
    }

    /**
     * Test attribute "exp_date"
     */
    public function testPropertyExpDate()
    {
    }

    /**
     * Test attribute "masked_card"
     */
    public function testPropertyMaskedCard()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }
}
