<?php
/**
 * ChargeSourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ChargeSourceTest Class Doc Comment
 *
 * @category    Class
 * @description ChargeSource
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChargeSourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChargeSource"
     */
    public function testChargeSource()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "card"
     */
    public function testPropertyCard()
    {
    }

    /**
     * Test attribute "fingerprint"
     */
    public function testPropertyFingerprint()
    {
    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {
    }

    /**
     * Test attribute "auth_transaction"
     */
    public function testPropertyAuthTransaction()
    {
    }

    /**
     * Test attribute "card_type"
     */
    public function testPropertyCardType()
    {
    }

    /**
     * Test attribute "exp_date"
     */
    public function testPropertyExpDate()
    {
    }

    /**
     * Test attribute "masked_card"
     */
    public function testPropertyMaskedCard()
    {
    }

    /**
     * Test attribute "strong_authentication_status"
     */
    public function testPropertyStrongAuthenticationStatus()
    {
    }

    /**
     * Test attribute "acquirer_code"
     */
    public function testPropertyAcquirerCode()
    {
    }

    /**
     * Test attribute "acquirer_message"
     */
    public function testPropertyAcquirerMessage()
    {
    }

    /**
     * Test attribute "acquirer_reference"
     */
    public function testPropertyAcquirerReference()
    {
    }

    /**
     * Test attribute "text_on_statement"
     */
    public function testPropertyTextOnStatement()
    {
    }
}
