<?php
/**
 * CheckoutSessionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CheckoutSessionTest Class Doc Comment
 *
 * @category    Class
 * @description CheckoutSession
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CheckoutSessionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CheckoutSession"
     */
    public function testCheckoutSession()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "result"
     */
    public function testPropertyResult()
    {
    }

    /**
     * Test attribute "error_code"
     */
    public function testPropertyErrorCode()
    {
    }

    /**
     * Test attribute "error_message"
     */
    public function testPropertyErrorMessage()
    {
    }

    /**
     * Test attribute "logo"
     */
    public function testPropertyLogo()
    {
    }

    /**
     * Test attribute "configuration"
     */
    public function testPropertyConfiguration()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "cancel_url"
     */
    public function testPropertyCancelUrl()
    {
    }

    /**
     * Test attribute "accept_url"
     */
    public function testPropertyAcceptUrl()
    {
    }

    /**
     * Test attribute "payment_methods"
     */
    public function testPropertyPaymentMethods()
    {
    }

    /**
     * Test attribute "subscription_invoice"
     */
    public function testPropertySubscriptionInvoice()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "charge"
     */
    public function testPropertyCharge()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "subscription"
     */
    public function testPropertySubscription()
    {
    }

    /**
     * Test attribute "plan"
     */
    public function testPropertyPlan()
    {
    }

    /**
     * Test attribute "add_ons"
     */
    public function testPropertyAddOns()
    {
    }

    /**
     * Test attribute "discounts"
     */
    public function testPropertyDiscounts()
    {
    }

    /**
     * Test attribute "subscription_payment_methods"
     */
    public function testPropertySubscriptionPaymentMethods()
    {
    }

    /**
     * Test attribute "recurring"
     */
    public function testPropertyRecurring()
    {
    }

    /**
     * Test attribute "settle"
     */
    public function testPropertySettle()
    {
    }

    /**
     * Test attribute "pkey"
     */
    public function testPropertyPkey()
    {
    }

    /**
     * Test attribute "strong_auth"
     */
    public function testPropertyStrongAuth()
    {
    }

    /**
     * Test attribute "payment_method"
     */
    public function testPropertyPaymentMethod()
    {
    }

    /**
     * Test attribute "pgw_url"
     */
    public function testPropertyPgwUrl()
    {
    }

    /**
     * Test attribute "mpo_url"
     */
    public function testPropertyMpoUrl()
    {
    }

    /**
     * Test attribute "mpo_session_token"
     */
    public function testPropertyMpoSessionToken()
    {
    }

    /**
     * Test attribute "mpo_version"
     */
    public function testPropertyMpoVersion()
    {
    }

    /**
     * Test attribute "viabill_url"
     */
    public function testPropertyViabillUrl()
    {
    }

    /**
     * Test attribute "resurs_url"
     */
    public function testPropertyResursUrl()
    {
    }

    /**
     * Test attribute "applepay_payment_request"
     */
    public function testPropertyApplepayPaymentRequest()
    {
    }

    /**
     * Test attribute "googlepay_payment_request"
     */
    public function testPropertyGooglepayPaymentRequest()
    {
    }

    /**
     * Test attribute "paypal_client_id"
     */
    public function testPropertyPaypalClientId()
    {
    }

    /**
     * Test attribute "paypal_payment_request"
     */
    public function testPropertyPaypalPaymentRequest()
    {
    }

    /**
     * Test attribute "paypal_auth_url"
     */
    public function testPropertyPaypalAuthUrl()
    {
    }

    /**
     * Test attribute "button_text"
     */
    public function testPropertyButtonText()
    {
    }

    /**
     * Test attribute "show_subscription_details"
     */
    public function testPropertyShowSubscriptionDetails()
    {
    }

    /**
     * Test attribute "show_terms"
     */
    public function testPropertyShowTerms()
    {
    }

    /**
     * Test attribute "card_on_file"
     */
    public function testPropertyCardOnFile()
    {
    }
}
