<?php
/**
 * CreatePreparedSubscriptionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * CreatePreparedSubscriptionTest Class Doc Comment
 *
 * @category    Class
 * @description CreatePreparedSubscription
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreatePreparedSubscriptionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreatePreparedSubscription"
     */
    public function testCreatePreparedSubscription()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "plan"
     */
    public function testPropertyPlan()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "handle"
     */
    public function testPropertyHandle()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }

    /**
     * Test attribute "create_customer"
     */
    public function testPropertyCreateCustomer()
    {
    }

    /**
     * Test attribute "plan_version"
     */
    public function testPropertyPlanVersion()
    {
    }

    /**
     * Test attribute "amount_incl_vat"
     */
    public function testPropertyAmountInclVat()
    {
    }

    /**
     * Test attribute "generate_handle"
     */
    public function testPropertyGenerateHandle()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "grace_duration"
     */
    public function testPropertyGraceDuration()
    {
    }

    /**
     * Test attribute "no_trial"
     */
    public function testPropertyNoTrial()
    {
    }

    /**
     * Test attribute "no_setup_fee"
     */
    public function testPropertyNoSetupFee()
    {
    }

    /**
     * Test attribute "subscription_discounts"
     */
    public function testPropertySubscriptionDiscounts()
    {
    }

    /**
     * Test attribute "coupon_codes"
     */
    public function testPropertyCouponCodes()
    {
    }

    /**
     * Test attribute "add_ons"
     */
    public function testPropertyAddOns()
    {
    }

    /**
     * Test attribute "additional_costs"
     */
    public function testPropertyAdditionalCosts()
    {
    }
}
