<?php
/**
 * GooglepayPaymentRequestDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * GooglepayPaymentRequestDtoTest Class Doc Comment
 *
 * @category    Class
 * @description GooglepayPaymentRequestDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GooglepayPaymentRequestDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GooglepayPaymentRequestDto"
     */
    public function testGooglepayPaymentRequestDto()
    {
    }

    /**
     * Test attribute "auth_url"
     */
    public function testPropertyAuthUrl()
    {
    }

    /**
     * Test attribute "environment"
     */
    public function testPropertyEnvironment()
    {
    }

    /**
     * Test attribute "api_version"
     */
    public function testPropertyApiVersion()
    {
    }

    /**
     * Test attribute "api_version_minor"
     */
    public function testPropertyApiVersionMinor()
    {
    }

    /**
     * Test attribute "merchant_info"
     */
    public function testPropertyMerchantInfo()
    {
    }

    /**
     * Test attribute "transaction_info"
     */
    public function testPropertyTransactionInfo()
    {
    }

    /**
     * Test attribute "allowed_payment_methods"
     */
    public function testPropertyAllowedPaymentMethods()
    {
    }
}
