<?php
/**
 * TransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Transaction
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Transaction"
     */
    public function testTransaction()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "settled"
     */
    public function testPropertySettled()
    {
    }

    /**
     * Test attribute "authorized"
     */
    public function testPropertyAuthorized()
    {
    }

    /**
     * Test attribute "failed"
     */
    public function testPropertyFailed()
    {
    }

    /**
     * Test attribute "refunded"
     */
    public function testPropertyRefunded()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "card_transaction"
     */
    public function testPropertyCardTransaction()
    {
    }

    /**
     * Test attribute "mpo_transaction"
     */
    public function testPropertyMpoTransaction()
    {
    }

    /**
     * Test attribute "applepay_transaction"
     */
    public function testPropertyApplepayTransaction()
    {
    }

    /**
     * Test attribute "googlepay_transaction"
     */
    public function testPropertyGooglepayTransaction()
    {
    }

    /**
     * Test attribute "manual_transaction"
     */
    public function testPropertyManualTransaction()
    {
    }

    /**
     * Test attribute "viabill_transaction"
     */
    public function testPropertyViabillTransaction()
    {
    }

    /**
     * Test attribute "resurs_transaction"
     */
    public function testPropertyResursTransaction()
    {
    }

    /**
     * Test attribute "paypal_transaction"
     */
    public function testPropertyPaypalTransaction()
    {
    }

    /**
     * Test attribute "pgw_transaction"
     */
    public function testPropertyPgwTransaction()
    {
    }
}
