<?php
/**
 * CheckoutApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CheckoutApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CheckoutApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for chargeCheckoutSession
     *
     * Finish charge using source.
     *
     */
    public function testChargeCheckoutSession()
    {
    }

    /**
     * Test case for createApplepaySession
     *
     * Create Apple Pay session.
     *
     */
    public function testCreateApplepaySession()
    {
    }

    /**
     * Test case for createGooglepaySession
     *
     * Create Google Pay session.
     *
     */
    public function testCreateGooglepaySession()
    {
    }

    /**
     * Test case for createMpoSession
     *
     * Create MobilePay Online session.
     *
     */
    public function testCreateMpoSession()
    {
    }

    /**
     * Test case for createPaypalSession
     *
     * Create PayPal session.
     *
     */
    public function testCreatePaypalSession()
    {
    }

    /**
     * Test case for createPgwSession
     *
     * Create pgw session.
     *
     */
    public function testCreatePgwSession()
    {
    }

    /**
     * Test case for createResursSession
     *
     * Create Resurs session.
     *
     */
    public function testCreateResursSession()
    {
    }

    /**
     * Test case for createViabillSession
     *
     * Create ViaBill session.
     *
     */
    public function testCreateViabillSession()
    {
    }

    /**
     * Test case for getCheckoutSession
     *
     * Get checkout session data.
     *
     */
    public function testGetCheckoutSession()
    {
    }

    /**
     * Test case for getResursPaymentMethodCost
     *
     * Get HTML with cost of Resurs payment method.
     *
     */
    public function testGetResursPaymentMethodCost()
    {
    }

    /**
     * Test case for getResursPaymentMethods
     *
     * Get Resurs payment methods.
     *
     */
    public function testGetResursPaymentMethods()
    {
    }

    /**
     * Test case for getTerms
     *
     * Get account terms template.
     *
     */
    public function testGetTerms()
    {
    }

    /**
     * Test case for recurringCheckoutSession
     *
     * Save recurring customer payment method.
     *
     */
    public function testRecurringCheckoutSession()
    {
    }

    /**
     * Test case for subscriptionCheckoutSession
     *
     * Set payment method on subscription.
     *
     */
    public function testSubscriptionCheckoutSession()
    {
    }
}
