<?php
/**
 * ConfigurationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConfigurationApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConfigurationApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createConfiguration
     *
     * Create configuration.
     *
     */
    public function testCreateConfiguration()
    {
    }

    /**
     * Test case for deleteConfiguration
     *
     * Delete configuration.
     *
     */
    public function testDeleteConfiguration()
    {
    }

    /**
     * Test case for getConfiguration
     *
     * Get configuration.
     *
     */
    public function testGetConfiguration()
    {
    }

    /**
     * Test case for getConfigurations
     *
     * Get configurations.
     *
     */
    public function testGetConfigurations()
    {
    }

    /**
     * Test case for updateConfiguration
     *
     * Update configuration.
     *
     */
    public function testUpdateConfiguration()
    {
    }
}
