<?php
/**
 * SignupApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Reepay Checkout API
 *
 * Reepay Checkout REST API
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.10
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * SignupApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SignupApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createSignupPage
     *
     * Create signup page.
     *
     */
    public function testCreateSignupPage()
    {
    }

    /**
     * Test case for deleteSignupPage
     *
     * Delete signup page.
     *
     */
    public function testDeleteSignupPage()
    {
    }

    /**
     * Test case for getSignupPage
     *
     * Get signup page.
     *
     */
    public function testGetSignupPage()
    {
    }

    /**
     * Test case for getSignupPageSignup
     *
     * Get signup page signup data.
     *
     */
    public function testGetSignupPageSignup()
    {
    }

    /**
     * Test case for getSignupPages
     *
     * Get signup pages.
     *
     */
    public function testGetSignupPages()
    {
    }

    /**
     * Test case for updateSignupPage
     *
     * Update signup page.
     *
     */
    public function testUpdateSignupPage()
    {
    }
}
